def packing_slip_tracking_status(status_code):
	status_dict = {
		'PF':'Plane in Flight',
		'AA':'At Airport',
		'PL':'Plane Landed',
		'AC':'At Canada Post facility', 
		'PM':'In Progress',
		'AD':'At Delivery', 
		'PU':'Picked Up',
		'AF':'At FedEx Facility', 
		'PX':'Picked up (see Details)',
		'AP':'At Pickup',
		'RR':'CDO requested',
		'AR':'Arrived at',
		'RM':'CDO Modified',
		'AX':'At USPS facility',
		'RC':'CDO Cancelled OR Recipient',
		'CA':'Shipment Cancelled',
		'RS':'Return to Shipper',
		'CH':'Location Changed ',
		'RP':'Return label link emailed to return sender',
		'DD':'Delivery Delay',
		'LP':'Return label link cancelled by shipment originator',
		'DE':'Delivery Exception',
		'RG':'Return label link expiring soon',
		'DL':'Delivered', 
		'RD':'Return label link expired',
		'DP':'Departed', 
		'SE':'Shipment Exception',
		'DR':'Vehicle furnished but not used',
		'SF':'At Sort Facility',
		'DS':'Vehicle Dispatched', 
		'SP':'Split Status',
		'DY':'Delay',
		'TR':'Transfer',	
		'EA':'Enroute to Airport OR Export Approved',
		'ED':'Enroute to Delivery',
		'CC':'Cleared Customs',
		'EO':'Enroute to Origin Airport',
		'CD':'Clearance Delay',
		'EP':'Enroute to Pickup', 
		'CP':'Clearance in Progress',
		'FD':'At FedEx Destination',
		'HL':'Hold at Location',	
		'IT':'In Transit',	
		'IX':'In transit (see Details)',
		'CA':'Carrier',
		'LO':'Left Origin',
		'OC':'Order Created', 
		'SH':'Shipper',
		'OD':'Out for Delivery', 
		'CU':'Customs',
		'OF':'At FedEx origin facility', 
		'BR':'Broker',
		'OX':'Shipment information sent to USPS', 
		'TP':'Transfer Partner',
		'PD':'Pickup Delay'
	}
	
	try:
		response = status_dict[status_code]
		return response
	except KeyError,e:
		frappe.throw("Unknown status found, Please contact to developer.")